language:
  - php
  - c

compiler:
  - gcc
  - clang

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - phpize && ./configure CFLAGS="-O2 -Wall -Wextra -Werror -Wno-unused-parameter" --silent && make --silent

script:
  - NO_INTERACTIVE=1 make test
