language: php

sudo: false

env:
  global:
    - secure: "kcXR42J1qdMXfSak0cQY/WF0pdfyXWIZEdH1ioyk30SFgKnBcDm5zWI6huYWoYvp0155bRAhwC93QbNlsZjyS6phjADotJl9iYGk32vAY+FqfMY+Y9qPMpjjK6X81r7aVNnMGWL/NzKwAya017vHvQg7Ekz8asfD0dS3YyRPsIm4BA/nLRZEOB9Bbkbn1ty/sHIwEi0prFO3+yf2Q9gx/b9dwkRYUKDEoZuBMHFkUroP6Mm7p6AUsRk1mHiM2+99cVBSAkmRZfzn5Nb88BTcknFlyodFzEt1MyjutclydnjReQq2KlEmWb6FdsE2G3cgplLEdBkmM43/l7czHMTSCpOXNbpG1sVE79kvf0KFjjgBECQYqn8mDbUcjlMiehz+Wx77994IvJ/GfFdGlyZr3owSqHv1KGD88Pj3kBXxIunHK/Urs8yxF08eL8tbx+3uKxo0d5ed3OjH4AYDqQjbGo3z3D2i5AVUxtA4tjFBOaoBvVXqs/RZY6RXt1/w7t2WVXtOxJnosTpNSCDYHvWlzZqLB5GJTzRxsPgcvxqGCJ9E3m/3TD+HJkcLA/pJWWR1wgVf9Yjx72x5nxXlY8Av5vGLsbpQd8Xi8gr0k0qzL1+lLADPh31MOR580ploNee8xjcZDbYVERJOKK6i83NFcWwkg2n0lxoK8k0fxSRTfP4="

php:
  - 7.1

addons:
  coverity_scan:
    project:
      name: "sjinks/php_nestinglevel"
      description: "Build submitted via Travis CI"
    notification_email: volodymyr@wildwolf.name
    build_command_prepend: "phpize && ./configure"
    build_command: "make -j 4"
    branch_pattern: coverity

script:
  - make
